### ISSUE TITLE
Use as part of container set

### ISSUE THREAD

**Issue by defconjuan** [dockerizedrupal/docker-vsftpd#9]
I'd like to add this to the default set of containers (apache, mysql, phpmyadmin, adminer, mailcatcher, etc.) that spins up when I create a set of containers from the docker-compose.yml file.

Do I need to add entries to the docker-compose.yml file and if so, what would it look like? Ideally, this would share mounts with the apache and/or mysql containers. I can handle port binding.

**Comment by viljaste** [comment]
Hey @defconjuan,

I'm going to try to explain the set up process with this Drupal 8 docker-compose.yml file:

`docker-compose.yml`

```
# Configuration generated with Drupal Compose version 1.3.1
apache:
  extends:
    file: host.yml
    service: apache
  image: dockerizedrupal/apache-2.4:1.2.4
  hostname: apache
  ports:
    - "80"
    - "443"
  volumes_from:
    - apache-data
  links:
    - php
  environment:
    - NO_GZIP=On
    - VHOST_PROJECT_NAME=my-project
    - VHOST_PRIMARY_SERVICE=True
    - VHOST_SERVICE_NAME=apache
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-apache-2.4/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/apache-2.4/
apache-data:
  image: dockerizedrupal/apache-2.4:1.2.4
  hostname: apache-data
  entrypoint: ["/bin/echo", "Data-only container for Apache."]
  volumes:
    - .:/apache/data
    - ../config:/apache/config
mysql:
  image: dockerizedrupal/mysql:1.2.2
  hostname: mysql
  volumes_from:
    - mysql-data
  environment:
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=mysql
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-mysql/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/mysql/
mysql-data:
  image: dockerizedrupal/mysql:1.2.2
  hostname: mysql-data
  entrypoint: ["/bin/echo", "Data-only container for MySQL."]
  volumes:
    - /mysql
php:
  extends:
    file: host.yml
    service: php
  image: dockerizedrupal/php-7.0:1.1.3
  hostname: php
  volumes:
    - ~/.ssh:/home/container/.ssh
  volumes_from:
    - apache-data
  links:
    - mysql
    - mailcatcher:smtp
    - memcached
  environment:
    - DRUPAL_VERSION=8
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=php
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-php-5.5/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/php-5.5/
    - PHP_INI_XDEBUG_VAR_DISPLAY_MAX_DEPTH=5
    - PHP_INI_MEMORY_LIMIT=180M
    - PHP_INI_MAX_EXECUTION_TIME=30
mailcatcher:
  image: dockerizedrupal/mailcatcher:1.1.1
  hostname: mailcatcher
  environment:
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=mailcatcher
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-mailcatcher/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/mailcatcher/
phpmyadmin:
  image: dockerizedrupal/phpmyadmin:1.1.1
  hostname: phpmyadmin
  links:
    - mysql
  environment:
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=phpmyadmin
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-phpmyadmin/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/phpmyadmin/
adminer:
  image: dockerizedrupal/adminer:1.1.1
  hostname: adminer
  links:
    - mysql
  environment:
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=adminer
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-adminer/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/adminer/
memcached:
  image: dockerizedrupal/memcached:1.1.0
  hostname: memcached
  environment:
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=memcached
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-memcached/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/memcached/
memcachephp:
  image: dockerizedrupal/memcachephp:1.1.1
  hostname: memcachephp
  links:
    - memcached
  environment:
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=memcachedphp
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-memcachephp/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/memcachephp/
```

To make it work with vsftpd, you simply have to add vsftpd configuration to docker-compose.yml file as follows:

`docker-compose.yml`

```
# Configuration generated with Drupal Compose version 1.3.1
apache:
  extends:
    file: host.yml
    service: apache
  image: dockerizedrupal/apache-2.4:1.2.4
  hostname: apache
  ports:
    - "80"
    - "443"
  volumes_from:
    - apache-data
  links:
    - php
  environment:
    - NO_GZIP=On
    - VHOST_PROJECT_NAME=my-project
    - VHOST_PRIMARY_SERVICE=True
    - VHOST_SERVICE_NAME=apache
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-apache-2.4/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/apache-2.4/
apache-data:
  image: dockerizedrupal/apache-2.4:1.2.4
  hostname: apache-data
  entrypoint: ["/bin/echo", "Data-only container for Apache."]
  volumes:
    - .:/apache/data
    - ../config:/apache/config
mysql:
  image: dockerizedrupal/mysql:1.2.2
  hostname: mysql
  volumes_from:
    - mysql-data
  environment:
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=mysql
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-mysql/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/mysql/
mysql-data:
  image: dockerizedrupal/mysql:1.2.2
  hostname: mysql-data
  entrypoint: ["/bin/echo", "Data-only container for MySQL."]
  volumes:
    - /mysql
php:
  extends:
    file: host.yml
    service: php
  image: dockerizedrupal/php-7.0:1.1.3
  hostname: php
  volumes:
    - ~/.ssh:/home/container/.ssh
  volumes_from:
    - apache-data
  links:
    - mysql
    - mailcatcher:smtp
    - memcached
  environment:
    - DRUPAL_VERSION=8
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=php
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-php-5.5/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/php-5.5/
    - PHP_INI_XDEBUG_VAR_DISPLAY_MAX_DEPTH=5
    - PHP_INI_MEMORY_LIMIT=180M
    - PHP_INI_MAX_EXECUTION_TIME=30
mailcatcher:
  image: dockerizedrupal/mailcatcher:1.1.1
  hostname: mailcatcher
  environment:
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=mailcatcher
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-mailcatcher/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/mailcatcher/
phpmyadmin:
  image: dockerizedrupal/phpmyadmin:1.1.1
  hostname: phpmyadmin
  links:
    - mysql
  environment:
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=phpmyadmin
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-phpmyadmin/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/phpmyadmin/
adminer:
  image: dockerizedrupal/adminer:1.1.1
  hostname: adminer
  links:
    - mysql
  environment:
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=adminer
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-adminer/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/adminer/
memcached:
  image: dockerizedrupal/memcached:1.1.0
  hostname: memcached
  environment:
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=memcached
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-memcached/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/memcached/
memcachephp:
  image: dockerizedrupal/memcachephp:1.1.1
  hostname: memcachephp
  links:
    - memcached
  environment:
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=memcachedphp
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-memcachephp/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/memcachephp/
vsftpd:
  image: dockerizedrupal/vsftpd:1.1.3
  hostname: vsftpd
  ports:
    - "20:20"
    - "21:21"
    - "50000-50002:50000-50002"
  volumes_from:
    - apache-data
  environment:
    - VSFTPD_1_USERNAME=my-ftp-username
    - VSFTPD_1_PASSWORD=my-ftp-password
    - VSFTPD_1_HOME=/apache/data
    - VSFTPD_1_USER_ID=1000
    - VSFTPD_1_GROUP_ID=1000
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=vsftpd
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-vsftpd/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/vsftpd/
```

It is recommended that you move `VSFTPD_1_USERNAME` and `VSFTPD_1_PASSWORD` environment variables to `host.yml` file, since they are host specific configuration:

`docker-compose.yml`

```
# Configuration generated with Drupal Compose version 1.3.1
apache:
  extends:
    file: host.yml
    service: apache
  image: dockerizedrupal/apache-2.4:1.2.4
  hostname: apache
  ports:
    - "80"
    - "443"
  volumes_from:
    - apache-data
  links:
    - php
  environment:
    - NO_GZIP=On
    - VHOST_PROJECT_NAME=my-project
    - VHOST_PRIMARY_SERVICE=True
    - VHOST_SERVICE_NAME=apache
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-apache-2.4/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/apache-2.4/
apache-data:
  image: dockerizedrupal/apache-2.4:1.2.4
  hostname: apache-data
  entrypoint: ["/bin/echo", "Data-only container for Apache."]
  volumes:
    - .:/apache/data
    - ../config:/apache/config
mysql:
  image: dockerizedrupal/mysql:1.2.2
  hostname: mysql
  volumes_from:
    - mysql-data
  environment:
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=mysql
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-mysql/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/mysql/
mysql-data:
  image: dockerizedrupal/mysql:1.2.2
  hostname: mysql-data
  entrypoint: ["/bin/echo", "Data-only container for MySQL."]
  volumes:
    - /mysql
php:
  extends:
    file: host.yml
    service: php
  image: dockerizedrupal/php-7.0:1.1.3
  hostname: php
  volumes:
    - ~/.ssh:/home/container/.ssh
  volumes_from:
    - apache-data
  links:
    - mysql
    - mailcatcher:smtp
    - memcached
  environment:
    - DRUPAL_VERSION=8
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=php
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-php-5.5/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/php-5.5/
    - PHP_INI_XDEBUG_VAR_DISPLAY_MAX_DEPTH=5
    - PHP_INI_MEMORY_LIMIT=180M
    - PHP_INI_MAX_EXECUTION_TIME=30
mailcatcher:
  image: dockerizedrupal/mailcatcher:1.1.1
  hostname: mailcatcher
  environment:
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=mailcatcher
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-mailcatcher/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/mailcatcher/
phpmyadmin:
  image: dockerizedrupal/phpmyadmin:1.1.1
  hostname: phpmyadmin
  links:
    - mysql
  environment:
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=phpmyadmin
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-phpmyadmin/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/phpmyadmin/
adminer:
  image: dockerizedrupal/adminer:1.1.1
  hostname: adminer
  links:
    - mysql
  environment:
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=adminer
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-adminer/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/adminer/
memcached:
  image: dockerizedrupal/memcached:1.1.0
  hostname: memcached
  environment:
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=memcached
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-memcached/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/memcached/
memcachephp:
  image: dockerizedrupal/memcachephp:1.1.1
  hostname: memcachephp
  links:
    - memcached
  environment:
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=memcachedphp
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-memcachephp/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/memcachephp/
vsftpd:
  extends:
    file: host.yml
    service: vsftpd
  image: dockerizedrupal/vsftpd:1.1.3
  hostname: vsftpd
  ports:
    - "20:20"
    - "21:21"
    - "50000-50002:50000-50002"
  volumes_from:
    - apache-data
  environment:
    - VSFTPD_1_USERNAME=my-ftp-username
    - VSFTPD_1_PASSWORD=my-ftp-password
    - VSFTPD_1_HOME=/apache/data
    - VHOST_PROJECT_NAME=my-project
    - VHOST_SERVICE_NAME=vsftpd
    - VHOST_VERSION_FILE_URL=https://raw.githubusercontent.com/dockerizedrupal/docker-vsftpd/master/VERSION.md
    - VHOST_REPOSITORY_URL=https://hub.docker.com/r/dockerizedrupal/vsftpd/
```

`host.yml`

```
# Configuration generated with Drupal Compose version 1.3.2
apache:
  environment:
    - USER_ID=1000
    - GROUP_ID=1000
php:
  environment:
    - USER_ID=1000
    - GROUP_ID=1000
vsftpd:
  environment:
    - VSFTPD_1_USER_ID=1000
    - VSFTPD_1_GROUP_ID=1000
```

The `VSFTPD_1_HOME` environment variable controls which directory is accessible through FTP. In this example it is set to `/apache/data`, which is the project root directory inside the Apache/PHP container. So for example if you only want to access Drupal files directory through FTP, set it to `/apache/data/sites/default/files`.
